from backend.database.mongo_db import DatabaseOperations
from datetime import datetime

db = DatabaseOperations()


receipts = db.db['receipts']

receipt_2149 = {
    "_id": "2149",
    "user_id": "user_1",
    "created_at": "06.02.2024 08:52",
    "uploaded_at": datetime.now().strftime("%d.%m.%Y %H:%M"),
    "store": {
        "id": "0007",
        "name": "KIWI LANGMYRVEIEN",
        "code": "KIWI"
  },
    "items": [
        { "name": "MILO TØYVASK",
          "size": "595",
          "unit": "milliliter",
          "quantity": 1,
          "price": 56.40,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "RISGRØT",
          "brand": "FJORDLAND",
          "size": "970",
          "unit": "gram",
          "quantity": 2,
          "price": 33.60,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "TØRKERULL",
          "size": "4",
          "unit": "RULL",
          "quantity": 1,
          "price": 42.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "FROKOSTEGG FRITTGÅENDE",
          "size": "12",
          "unit": "STK",
          "quantity": 1,
          "price": 42.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "LETTRØMME",
          "size": "300",
          "unit": "gram",
          "quantity": 1,
          "price": 19.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "KARBONADEDEIG",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 81.50,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "TORTILLA ORIGINAL LARGE",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 27.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "PAPRIKA RØD",
          "size": "194",
          "unit": "gram",
          "quantity": 1,
          "price": 13.17,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "CRISPISALAT",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 24.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "MANGO TØRKET",
          "size": "60",
          "unit": "gram",
          "quantity": 1,
          "price": 22.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "AVOCADO 2PK MODEN SEASON",
          "size": "2",
          "unit": "PK",
          "quantity": 1,
          "price": 39.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "AGURK",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 24.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "LIME",
          "size": "78",
          "unit": "gram",
          "quantity": 1,
          "price": 5.45,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "MELKESJOKOLADE KVIKKLUNSJ",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 24.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        }

    ],
    "total": 465.47,
    "total_discount": None
  }

receipt_2150 = {
    "_id": "2150",
    "user_id": "user_2",
    "created_at": "04.12.2023 12:52",
    "uploaded_at": datetime.now().strftime("%d.%m.%Y %H:%M"),
    "store": {
        "id": "0008",
        "name": "EUROSPAR MOLDE",
        "code": "EUROSPAR"
    },
    "items": [
        { "name": "RULLEKEBAB DØNER MIX",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 69.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        }
    ],
    "total": 69.90,
    "total_discount": None
}

receipt_2151 = {
    "_id": "2151",
    "user_id": "user_3",
    "created_at": "29.11.2023 19:19",
    "uploaded_at": datetime.now().strftime("%d.%m.%Y %H:%M"),
    "store": {
        "id": "0009",
        "name": "KIWI GRANDFJÆRA",
        "code": "KIWI"
    },
    "items": [
        { "name": "COCA-COLA U/SUKKER",
          "size": "1.5",
          "unit": "liter",
          "quantity": 6,
          "price": 79.00,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "RUNDSTYKKER GROVE",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 38.40,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "POTETER MANDEL",
          "size": "2",
          "unit": "KG",
          "quantity": 1,
          "price": 19.80,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "APPELSINJUICE PREMIUM",
          "size": "1",
          "unit": "liter",
          "quantity": 1,
          "price": 23.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "LETTMELK",
          "size": "1",
          "unit": "liter",
          "quantity": 1,
          "price": 18.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "NORVEGIA",
          "size": "500",
          "unit": "gram",
          "quantity": 1,
          "price": 66.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "MEIERISMØR",
          "size": "250",
          "unit": "gram",
          "quantity": 1,
          "price": 31.40,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "MARGARIN FLYTENDE",
          "size": "500",
          "unit": "milliliter",
          "quantity": 1,
          "price": 35.30,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "PESTO GENOVESE",
          "brand": "BARILLA",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 21.40,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "GRØNNSAKSBULJONG KLAR",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 16.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "KAVIAR TUBE",
          "brand": "MILLS",
          "size": "185",
          "unit": "gram",
          "quantity": 1,
          "price": 22.30,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "MAJONES EKTE",
          "size": "160",
          "unit": "gram",
          "quantity": 1,
          "price": 26.40,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "YOGHURT GRESK NATURELL",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 27.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "KARBONADEDEIG",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 81.50,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "SVIN YTREFILET FOLKETS",
          "size": "580",
          "unit": "gram",
          "quantity": 1,
          "price": 115.42,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "TRANEBÆR TØRKET",
          "size": "110",
          "unit": "gram",
          "quantity": 1,
          "price": 22.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "PINJEKJERNER NATURELL",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 22.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "RØDLØK STRØMP",
          "size": "2",
          "unit": "STK",
          "quantity": 1,
          "price": 19.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "CHIA FRØ",
          "size": "200",
          "unit": "gram",
          "quantity": 1,
          "price": 22.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "AGURK",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 24.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "SQUASH",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 19.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "NACHIPS CRUNCHY",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 26.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "HVITLØK",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 16.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "TOMATER",
          "size": "175",
          "unit": "gram",
          "quantity": 1,
          "price": 32.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "CHILIPEPPER RØD",
          "size": "50",
          "unit": "gram",
          "quantity": 1,
          "price": 21.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "PAPRIKA RØD",
          "size": "386",
          "unit": "gram",
          "quantity": 2,
          "price": 25.43,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "PAPRIKA GRØNN",
          "size": "242",
          "unit": "gram",
          "quantity": 1,
          "price": 19.34,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "LIME",
          "size": "90",
          "unit": "gram",
          "quantity": 1,
          "price": 6.29,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "AVOCADO STK SEASON",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 32.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "CRISPISALAT",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 24.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        }
    ],
    "total": 992.78,
    "total_discount": None
}

receipt_2152 = {
    "_id": "2152",
    "user_id": "user_1",
    "created_at": "29.11.2023 14:26",
    "uploaded_at": datetime.now().strftime("%d.%m.%Y %H:%M"),
    "store": {
        "id": "0008",
        "name": "EUROSPAR MOLDE",
        "code": "EUROSPAR"
    },
    "items": [
        { "name": "RULLEKEBAB DØNER MIX",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 69.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "MANGO TØRKET",
          "size": "60",
          "unit": "gram",
          "quantity": 1,
          "price": 25.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        }
    ],
    "total": 95.80,
    "total_discount": None
}

receipt_2153 = {
    "_id": "2153",
    "user_id": "user_2",
    "created_at": "23.11.2023 16:53",
    "uploaded_at": datetime.now().strftime("%d.%m.%Y %H:%M"),
    "store": {
        "id": "0023",
        "name": "BUNNPRIS & GOURMET FUGLSET",
        "code": "BUNNPRIS"
    },
    "items": [
        { "name": "POTETBALL MEDIUM",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 149.00,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "NORVEGIA",
          "size": "500",
          "unit": "gram",
          "quantity": 1,
          "price": 75.50,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        }
    ],
    "total": 224.50,
    "total_discount": None
}

receipt_2154 = {
    "_id": "2154",
    "user_id": "user_3",
    "created_at": "11.11.2023 17:59",
    "uploaded_at": datetime.now().strftime("%d.%m.%Y %H:%M"),
    "store": {
        "id": "0007",
        "name": "KIWI LANGMYRVEIEN",
        "code": "KIWI"
    },
    "items": [
        { "name": "FRYDENLUND FATØL",
          "size": "0.5",
          "unit": "liter",
          "quantity": 6,
          "price": 197.40,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "SJOKO KRØNSJ",
          "size": "200",
          "unit": "gram",
          "quantity": 1,
          "price": 35.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "COLA-COLA",
          "size": "0.33",
          "unit": "liter",
          "quantity": 1,
          "price": 18.40,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "MANGO TØRKET",
          "size": "60",
          "unit": "gram",
          "quantity": 1,
          "price": 22.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        }
    ],
    "total": 292.85,
    "total_discount": None
}

receipt_2155 = {
    "_id": "2155",
    "user_id": "user_1",
    "created_at": "13.11.2023 22:13",
    "uploaded_at": datetime.now().strftime("%d.%m.%Y %H:%M"),
    "store": {
        "id": "0023",
        "name": "BUNNPRIS & GOURMET FUGLSET",
        "code": "BUNNPRIS"
    },
    "items": [
        { "name": "NACHIPS CRUNCHY",
          "brand": "ST.MARIA",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 17.94,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "TACO SPICE MIX",
         "brand": "ST.MARIA",
          "size": "84",
          "unit": "gram",
          "quantity": 3,
          "price": 15.54,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "TACOSAUS HOT",
         "brand": "ST.MARIA",
          "size": "230",
          "unit": "gram",
          "quantity": 1,
          "price": 16.14,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "LANO HÅNDSÅPE REFILL",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 25.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "TORTILLA M/RØDBET MEDIUM",
          "size": "240",
          "unit": "gram",
          "quantity": 1,
          "price": 21.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "TORTILLA ORIGINAL",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 17.94,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "MONSTER PIPELINE PUNCH",
          "size": "0.5",
          "unit": "liter",
          "quantity": 1,
          "price": 17.50,
          "discount": None,
          "discounted_price": 10.00,
          "price_original": 27.50
        },
        { "name": "MONSTER MANGO LOCO",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 17.50,
          "discount": None,
          "discounted_price": 10.00,
          "price_original": 27.50
        },
        { "name": "JIF EASY WIPE TOALETT OG BAD",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 29.95,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "MØLLEHJUL FULLKORN",
          "brand": "HATTING",
          "size": "420",
          "unit": "gram",
          "quantity": 1,
          "price": 42.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        }
    ],
    "total": 231.71,
    "total_discount": 20.00
}

receipt_2156 = {
    "_id": "2156",
    "user_id": "user_2",
    "created_at": "14.11.2023 19:27",
    "uploaded_at": datetime.now().strftime("%d.%m.%Y %H:%M"),
    "store": {
        "id": "0004",
        "name": "COOP MEGA MOLDELIVEIEN",
        "code": "COOP"
    },
    "items": [
        { "name": "FRYDENLUND FATØL",
          "size": "0.5",
          "unit": "liter",
          "quantity": 2,
          "price": 69.80,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "CHORIZO",
          "brand": "GRILSTAD",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 39.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "GRØNN ASPARGES",
          "size": "250",
          "unit": "gram",
          "quantity": 1,
          "price": 29.90,
          "discount": 58.4,
          "discounted_price": 42.00,
          "price_original": 71.90
        },
        { "name": "LIME",
          "size": "132",
          "unit": "gram",
          "quantity": 1,
          "price": 10.81,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "PINJEKERNER",
          "size": "30",
          "unit": "gram",
          "quantity": 1,
          "price": 32.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "SØTPOTET",
          "size": "306",
          "unit": "gram",
          "quantity": 1,
          "price": 14.66,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "TENNBRIKETTER",
          "size": "32",
          "unit": "STK",
          "quantity": 1,
          "price": 37.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        }
    ],
    "total": 244.12,
    "total_discount": 42.00
}

receipt_2157 = {
    "_id": "2157",
    "user_id": "user_3",
    "created_at": "16.03.2024 18:17",
    "uploaded_at": datetime.now().strftime("%d.%m.%Y %H:%M"),
    "store": {
        "id": "0023",
        "name": "BUNNPRIS & GOURMET FUGLSET",
        "code": "BUNNPRIS"
    },
    "items": [
        { "name": "pizza nr1 Kokkens favoritt",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 139.00,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "pizza nr4 Mexico",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 135.00,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "APPELSINJUICE KALDPRESSET",
          "brand": "RÅ",
          "size": "1",
          "unit": "liter",
          "quantity": 1,
          "price": 49.00,
          "discount": None,
          "discounted_price": 20.90,
          "price_original": 69.90
        },
        { "name": "FLØTEMYSOST SKIVET",
          "size": "130",
          "unit": "gram",
          "quantity": 1,
          "price": 26.50,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "FETASNACK SOLTØRKET TOMAT",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 20.00,
          "discount": None,
          "discounted_price": 7.50,
          "price_original": 27.50
        },
        { "name": "RUCCOLAMIX",
          "size": "175",
          "unit": "gram",
          "quantity": 1,
          "price": 29.90,
          "discount": None,
          "discounted_price": None,
          "price_original": None
        },
        { "name": "SMÅGODT LØS VEKT",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 38.87,
          "discount": None,
          "discounted_price": 39.36,
          "price_original": 78.23
        }
    ],
    "total": 441.27,
    "total_discount": 67.76
}

receipt_2159 = {
    "_id": "2159",
    "user_id": "user_1",
    "created_at": "01.03.2024 15:17",
    "uploaded_at": datetime.now().strftime("%d.%m.%Y %H:%M"),
    "store": {
        "id": "0023",
        "name": "BUNNPRIS & GOURMET FUGLSET",
        "code": "BUNNPRIS"
    },
    "items": [
        { "name": "KYLLINGFILET",
          "brand": "PRIOR",
          "size": "650",
          "unit": "gram",
          "quantity": 1,
          "price": 89.00,
          "discount": None,
          "discounted_price": 56.00,
          "price_original": 145.00
        },
        { "name": "WOK CHINESE",
          "brand": "ELDORADO",
          "size": "500",
          "unit": "gram",
          "quantity": 1,
          "price": 17.34,
          "discount": None,
          "discounted_price": 11.56,
          "price_original": 28.90
        },
        { "name": "BYGG -OG HAVRE RUNDSTYKKER",
          "size": "",
          "unit": "STK",
          "quantity": 1,
          "price": 35.00,
          "discount": None,
          "discounted_price": 10.50,
          "price_original": 45.50
        },
        { "name": "EKTE REVET OST ØKONIMIPK",
          "size": "370",
          "unit": "gram",
          "quantity": 1,
          "price": 40.00,
          "discount": None,
          "discounted_price": 15.90,
          "price_original": 55.90
        },
        { "name": "PIZZASAUS PEPPES",
          "size": "180",
          "unit": "gram",
          "quantity": 2,
          "price": 26.46,
          "discount": None,
          "discounted_price": 11.34,
          "price_original": 37.80
        },
        { "name": "KAVIAR TUBE",
          "brand": "MILLS",
          "size": "185",
          "unit": "gram",
          "quantity": 1,
          "price": 18.83,
          "discount": None,
          "discounted_price": 8.07,
          "price_original": 26.90
        },
        { "name": "JALAPENOS",
          "brand": "OLD EL PASO",
          "size": "250",
          "unit": "gram",
          "quantity": 1,
          "price": 17.94,
          "discount": None,
          "discounted_price": 11.96,
          "price_original": 29.90
        },
        { "name": "POTETGULL PAPRIKA KICK",
          "brand": "KIMS",
          "size": "200",
          "unit": "gram",
          "quantity": 1,
          "price": 14.90,
          "discount": None,
          "discounted_price": 22.00,
          "price_original": 36.90
        }
    ],
    "total": 259.47,
    "total_discount": 147.33
}

receipts.insert_many([receipt_2149, receipt_2150, receipt_2151, receipt_2152, receipt_2153, receipt_2154, receipt_2155, receipt_2156, receipt_2157, receipt_2159])